baseURL = "https://jhlee1.github.io/"
languageCode = "en-us"
title = "Code Repository"
theme = "jeffprod"

[permalinks]
  post = "/:year/:filename"

[taxonomies]
  tag = "tags"
  archive = "archives"

[Author]
    name="Joohan Lee"
